// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFwlMnd3jhf-5owSjKRh_vFwHiGHFt_Rw',
    appId: '1:397060480663:web:3fd857c29516e830e113d2',
    messagingSenderId: '397060480663',
    projectId: 'flutterapp-85d0d',
    authDomain: 'flutterapp-85d0d.firebaseapp.com',
    storageBucket: 'flutterapp-85d0d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNFCYOc7SeYxbGV8K83YXapTFet8_swuU',
    appId: '1:397060480663:android:6cca9c1f4d55942ee113d2',
    messagingSenderId: '397060480663',
    projectId: 'flutterapp-85d0d',
    storageBucket: 'flutterapp-85d0d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5P0Vv6aZWixsNHP8rRsPpN2C0OV2LKoQ',
    appId: '1:397060480663:ios:4ca2b9555bdf4733e113d2',
    messagingSenderId: '397060480663',
    projectId: 'flutterapp-85d0d',
    storageBucket: 'flutterapp-85d0d.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5P0Vv6aZWixsNHP8rRsPpN2C0OV2LKoQ',
    appId: '1:397060480663:ios:4ca2b9555bdf4733e113d2',
    messagingSenderId: '397060480663',
    projectId: 'flutterapp-85d0d',
    storageBucket: 'flutterapp-85d0d.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );
}
